#!/usr/bin/env python3
from __future__ import annotations

import argparse
import sys
from collections import defaultdict
from pathlib import Path

try:
    from cli_support import configure_utf8_stdio
except ModuleNotFoundError:
    from tools.cli_support import configure_utf8_stdio

try:
    from wiki_store import EVENTS, WIKI, load_concepts, parse_frontmatter, string_list
except ModuleNotFoundError:
    from tools.wiki_store import EVENTS, WIKI, load_concepts, parse_frontmatter, string_list


GENERATED_HEADER = "<!-- generated by tools/generate_event_indexes.py -->"


def markdown_text(value: object) -> str:
    return str(value).replace("#", "\\#")


def event_sort_key(item: tuple[Path, dict[str, object]]) -> tuple[str, str]:
    _path, data = item
    date = data.get("date")
    title = data.get("title")
    return (date if isinstance(date, str) else "", title if isinstance(title, str) else "")


def render_index(events: list[tuple[Path, dict[str, object]]], bundle: Path = WIKI) -> str:
    concepts = load_concepts(bundle)
    by_topic: dict[str, list[tuple[Path, dict[str, object]]]] = defaultdict(list)
    by_body: dict[str, list[tuple[Path, dict[str, object]]]] = defaultdict(list)
    for item in events:
        for topic in string_list(item[1], "topics"):
            by_topic[topic].append(item)
        for body in string_list(item[1], "bodies"):
            by_body[body].append(item)

    lines = [
        "# Events",
        "",
        GENERATED_HEADER,
        "",
        "このディレクトリは、勧告、action item、状態変更、重要な提案提出などの出来事を canonical summary として記録する。",
        "",
        "## All Events",
        "",
    ]

    for path, data in sorted(events, key=event_sort_key):
        title = markdown_text(data.get("title", path.stem))
        date = data.get("date", "")
        description = markdown_text(data.get("description", ""))
        lines.append(f"- [{title}]({path.name}) ({date}) - {description}")

    if by_topic:
        lines.extend(["", "## By Topic", ""])
        for topic in sorted(by_topic):
            concept = concepts.get(topic)
            heading = f"[{markdown_text(concept.title)}](../{concept.rel_path})" if concept else markdown_text(topic)
            lines.extend([f"### {heading}", ""])
            for path, data in sorted(by_topic[topic], key=event_sort_key):
                title = markdown_text(data.get("title", path.stem))
                date = data.get("date", "")
                lines.append(f"- [{title}]({path.name}) ({date})")
            lines.append("")

    if by_body:
        lines.extend(["## By Body", ""])
        for body in sorted(by_body):
            lines.extend([f"### {body}", ""])
            for path, data in sorted(by_body[body], key=event_sort_key):
                title = markdown_text(data.get("title", path.stem))
                date = data.get("date", "")
                lines.append(f"- [{title}]({path.name}) ({date})")
            lines.append("")

    return "\n".join(str(line) for line in lines).rstrip() + "\n"


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate event indexes by topic and body.")
    parser.add_argument("--check", action="store_true", help="Fail if the generated index differs.")
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    configure_utf8_stdio()
    args = parse_args(argv or sys.argv[1:])
    events: list[tuple[Path, dict[str, object]]] = []
    for path in sorted(EVENTS.glob("*.md")):
        if path.name == "index.md":
            continue
        data, errors = parse_frontmatter(path)
        if errors:
            raise SystemExit("\n".join(errors))
        events.append((path, data))

    index = EVENTS / "index.md"
    rendered = render_index(events)
    if args.check:
        if index.read_text(encoding="utf-8") != rendered:
            print(f"outdated: {index}", file=sys.stderr)
            return 1
        print(f"Event index up to date: {index}")
        return 0

    with index.open("w", encoding="utf-8", newline="") as handle:
        handle.write(rendered)
    print(f"Generated {index}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
