#!/usr/bin/env python3
from __future__ import annotations

from collections import defaultdict
from pathlib import Path

from check_events import EVENTS, parse_frontmatter, string_list


GENERATED_HEADER = "<!-- generated by tools/generate_event_indexes.py -->"


def event_sort_key(item: tuple[Path, dict[str, object]]) -> tuple[str, str]:
    _path, data = item
    date = data.get("date")
    title = data.get("title")
    return (date if isinstance(date, str) else "", title if isinstance(title, str) else "")


def main() -> int:
    events: list[tuple[Path, dict[str, object]]] = []
    for path in sorted(EVENTS.glob("*.md")):
        if path.name == "index.md":
            continue
        data, errors = parse_frontmatter(path)
        if errors:
            raise SystemExit("\n".join(errors))
        events.append((path, data))

    by_topic: dict[str, list[tuple[Path, dict[str, object]]]] = defaultdict(list)
    for item in events:
        for topic in string_list(item[1], "topics"):
            by_topic[topic].append(item)

    lines = [
        "# Events",
        "",
        GENERATED_HEADER,
        "",
        "このディレクトリは、勧告、action item、状態変更、重要な提案提出などの出来事を canonical summary として記録する。",
        "",
        "## All Events",
        "",
    ]

    for path, data in sorted(events, key=event_sort_key):
        title = data.get("title", path.stem)
        date = data.get("date", "")
        description = data.get("description", "")
        lines.append(f"- [{title}]({path.name}) ({date}) - {description}")

    if by_topic:
        lines.extend(["", "## By Topic", ""])
        for topic in sorted(by_topic):
            lines.extend([f"### {topic}", ""])
            for path, data in sorted(by_topic[topic], key=event_sort_key):
                title = data.get("title", path.stem)
                date = data.get("date", "")
                lines.append(f"- [{title}]({path.name}) ({date})")
            lines.append("")

    (EVENTS / "index.md").write_text("\n".join(str(line) for line in lines).rstrip() + "\n", encoding="utf-8")
    print(f"Generated {EVENTS / 'index.md'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
