#!/usr/bin/env python3
from __future__ import annotations

import argparse
import re
import sys
from collections import defaultdict
from pathlib import Path

try:
    from cli_support import configure_utf8_stdio
except ModuleNotFoundError:
    from tools.cli_support import configure_utf8_stdio

try:
    from wiki_store import WIKI, scalar, load_concepts
except ModuleNotFoundError:
    from tools.wiki_store import WIKI, scalar, load_concepts


INDEX_LINE_RE = re.compile(r"^- \[[^]]+\]\(([^)]+)\)(?: - (.*))?$")
REGISTRY_ORDER = ["utc", "wg2", "irg", "pri"]
REGISTRY_TITLES = {"utc": "UTC", "wg2": "WG2", "irg": "IRG", "pri": "PRI"}
GENERATED_HEADER = "<!-- generated by tools/generate_document_index.py -->"


def existing_descriptions(index_path: Path) -> dict[str, str]:
    descriptions: dict[str, str] = {}
    if not index_path.exists():
        return descriptions
    for line in index_path.read_text(encoding="utf-8").splitlines():
        match = INDEX_LINE_RE.match(line)
        if match and match.group(2):
            descriptions[Path(match.group(1)).name] = match.group(2)
    return descriptions


def render_index(bundle: Path) -> str:
    concepts = load_concepts(bundle)
    index_path = bundle / "documents" / "index.md"
    descriptions = existing_descriptions(index_path)
    grouped: dict[str, dict[str, list[object]]] = defaultdict(lambda: defaultdict(list))
    for concept in concepts.values():
        if concept.type != "Source Document":
            continue
        registry = scalar(concept.frontmatter, "registry") or "other"
        date = scalar(concept.frontmatter, "date")
        year = date[:4] if len(date) >= 4 and date[:4].isdigit() else "Undated"
        grouped[registry][year].append(concept)

    lines = [
        "# Documents", "", GENERATED_HEADER, "",
        "重要な Registry 文書の要約ページを置く。registry ごとに新しい年から並べる。ファイル名は `entry_id` に合わせる。", "",
    ]
    registries = REGISTRY_ORDER + sorted(set(grouped) - set(REGISTRY_ORDER))
    for registry in registries:
        if registry not in grouped:
            continue
        lines.extend([f"## {REGISTRY_TITLES.get(registry, registry.upper())}", ""])
        years = sorted(grouped[registry], key=lambda value: (value != "Undated", value), reverse=True)
        for year in years:
            lines.extend([f"### {year}", ""])
            items = sorted(grouped[registry][year], key=lambda concept: (scalar(concept.frontmatter, "date"), concept.id), reverse=True)
            for concept in items:
                label = (scalar(concept.frontmatter, "doc_number") or concept.title).replace("#", "\\#")
                description = descriptions.get(concept.path.name) or scalar(concept.frontmatter, "description") or concept.title
                lines.append(f"- [{label}]({concept.path.name}) - {description}")
            lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate the document index grouped by registry and year.")
    parser.add_argument("--check", action="store_true", help="Fail if the generated index differs.")
    parser.add_argument("--bundle", type=Path, default=WIKI)
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    configure_utf8_stdio()
    args = parse_args(argv or sys.argv[1:])
    path = args.bundle / "documents" / "index.md"
    rendered = render_index(args.bundle)
    if args.check:
        if path.read_text(encoding="utf-8") != rendered:
            print(f"outdated: {path}", file=sys.stderr)
            return 1
        print(f"Document index up to date: {path}")
        return 0
    with path.open("w", encoding="utf-8", newline="") as handle:
        handle.write(rendered)
    print(f"Generated {path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
